server:
  port: 8080

spring:
  application:
    name: document-intelligence-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/docintel
    username: docintel
    password: docintel
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
